# Generated by Django 3.0 on 2020-01-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20200103_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
    ]
