# Generated by Django 3.0 on 2020-08-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='lastChangeDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
