# Generated by Django 3.0 on 2020-08-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_todo_lastchangedatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lastChangeDateTime',
            field=models.DateTimeField(),
        ),
    ]
